import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),r=reporter(process.argv[3]),modeKey='wb_tab_ai_v1:1',txKey='wb_tab_ai_change_v1:1';
const save=(w,mode)=>w.call({type:'WB_SAVE_RUNTIME_OPTIONS',tab_id:1,options:{ai_mode:mode}});
async function test(id,fn){await r.test(id,async()=>{const w=boot(root);try{await fn(w);assert.equal(w.counts.provider,0);assert.equal(w.counts.promptDispatch,0)}finally{w.dispose()}})}
function receiver(w,behavior){const original=w.context.chrome.tabs.sendMessage;w.context.chrome.tabs.sendMessage=(id,m,cb)=>{if(m.type==='WB_APPLY_AI_MODE'){w.messages.push(m);const result=behavior(m);cb(result??{ok:true,applied:true,ai_mode:m.ai_mode,adapter_id:m.ai_mode==='alice'?null:'chatgpt',runtime_id:w.state.runtimeId,runtime_generation:w.state.generation});}else original(id,m,cb)}}
await test('SUCCESS_REQUIRES_CONTENT_APPLY_WITHOUT_REFRESH',async w=>{receiver(w,()=>{});const q=await save(w,'chatgpt');assert.equal(q.ok,true);assert.equal(w.messages.filter(m=>m.type==='WB_APPLY_AI_MODE').length,1);assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);assert.equal(q.options.ai_mode,'chatgpt');assert.equal(q.adapter_id,'chatgpt')});
await test('FAILED_APPLY_ROLLS_BACK_STORED_MODE',async w=>{w.data[modeKey]={mode:'chatgpt',origin:w.state.identity.origin};receiver(w,m=>m.ai_mode==='alice'?{ok:false,code:'FIXTURE_REJECTED'}:undefined);const q=await save(w,'alice');assert.equal(q.ok,false);assert.equal(w.data[modeKey].mode,'chatgpt');assert.equal(q.rollback_confirmed,true)});
await test('ROUTE_CHANGE_DURING_APPLY_REJECTS_COMMIT',async w=>{receiver(w,()=>{w.state.identity={...w.state.identity,conversation_id:'22222222-2222-2222-2222-222222222222'}});const q=await save(w,'chatgpt');assert.equal(q.ok,false);assert.notEqual(w.data[modeKey]?.mode,'chatgpt')});
await test('RESTART_PENDING_APPLY_USES_PRIOR_MODE',async w=>{w.data[modeKey]={mode:'alice',origin:w.state.identity.origin};w.data[txKey]={phase:'applying',origin:w.state.identity.origin,previous_mode:'chatgpt'};const q=await w.call({type:'WB_GET_RUNTIME_OPTIONS',tab_id:1});assert.equal(q.options.ai_mode,'chatgpt')});
await test('GLOBAL_AI_MODE_REJECTED',async w=>{const q=await w.call({type:'WB_SAVE_RUNTIME_OPTIONS',options:{ai_mode:'alice'}});assert.equal(q.ok,false);assert.equal(q.code,'GLOBAL_AI_MODE_REMOVED')});
r.finish({scope:'Per-tab AI apply/rollback with real worker; donor OZ_SET_TAB_AI_MODE contract plus durable pending mode; no provider traffic'});
