import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';
import {reporter} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),donor=path.resolve(process.argv[3]),log=reporter(process.argv[4]);
const load=(dir,ns)=>{const c=vm.createContext({URL,TextEncoder});for(const f of ['shared/ai_delivery_capabilities.js','shared/conversation_identity.js'])vm.runInContext(fs.readFileSync(path.join(dir,f),'utf8'),c);return {context:c,caps:c[ns],identity:c.BB2ConversationIdentity}};
const w=load(root,'WBAIDeliveryCapabilities'),d=load(donor,'OzonAIDeliveryCapabilities'),j=v=>JSON.parse(JSON.stringify(v));
await log.test('IMPLEMENTED_TARGET_AUTHORITY_MATCHES_CURRENT_DONOR',()=>{assert.deepEqual(j(w.caps.implementedTargetIds()),j(d.caps.implementedTargetIds()));assert.deepEqual(j(w.caps.implementedContentScriptPatterns()),j(d.caps.implementedContentScriptPatterns()));for(const id of d.caps.TARGET_AI_IDS)for(const field of ['status','origins','conversation_path_segment','canonical_conversation_supported','active_conversation_evidence_required','composer_control_strategy','inline_mixed_text_with_files','pre_attachment_failure_text_fallback','max_files_per_turn','plain_text_length_metric'])assert.deepEqual(w.caps.profile(id)[field]===undefined?null:j(w.caps.profile(id)[field]),d.caps.profile(id)[field]===undefined?null:j(d.caps.profile(id)[field]),id+'.'+field)});
await log.test('EXACT_HTTPS_ORIGINS_REJECT_LOOKALIKES_AND_PLANNED',()=>{for(const origin of ['http://chatgpt.com','https://chatgpt.com.attacker.invalid','https://alice.yandex.ru:444','https://deepseek.com','https://chatgpt.com','https://chat.openai.com','https://alice.yandex.ru'])assert.equal(w.caps.adapterIdForOrigin(origin),d.caps.adapterIdForOrigin(origin),origin)});
const id='11111111-1111-1111-1111-111111111111',other='22222222-2222-2222-2222-222222222222';
await log.test('IDENTITY_SEMANTIC_DIFFERENTIAL_CURRENT_DONOR',()=>{for(const ai of ['chatgpt','alice'])for(const canonical of ['',id,other])for(const active of [null,id,other]){const origin=ai==='alice'?'https://alice.yandex.ru':'https://chatgpt.com',pathname=d.caps.conversationPathForTarget(ai,id),args={origin,pathname,canonicalHref:canonical?origin+'/c/'+canonical:'',activeConversationId:active},a=w.identity.resolveWithEvidence(args),b=d.identity.resolveWithEvidence(args);for(const field of ['status','conversation_id','ai_id','corroboration'])assert.equal(a[field],b[field],JSON.stringify({args,field}));}});
await log.test('SYNTHETIC_TARGET_IDENTITY_IS_CAPABILITY_DRIVEN',()=>{const c=vm.createContext({URL,TextEncoder, WBAIDeliveryCapabilities:{adapterIdForOrigin:o=>o==='https://fixture.invalid'?'fixture':null,profile:()=>({conversation_path_segment:'thread',active_conversation_evidence_required:true,canonical_conversation_supported:false}),conversationPathForTarget:(a,id)=>'/thread/'+id}});vm.runInContext(fs.readFileSync(path.join(root,'shared/conversation_identity.js'),'utf8'),c);const I=c.BB2ConversationIdentity,args={origin:'https://fixture.invalid',pathname:'/thread/'+id};assert.equal(I.resolveWithEvidence({...args,activeConversationId:id}).status,'confirmed');assert.equal(I.resolveWithEvidence(args).status,'unknown');assert.equal(I.conversationPathFor('fixture',id),'/thread/'+id)});
await log.test('TARGET_TEXT_BUDGET_METRICS_MATCH_CURRENT_DONOR',()=>{for(const ai of ['chatgpt','alice'])for(const text of ['', '😀'.repeat(45001),'x'.repeat(1048001)])assert.deepEqual(j(w.caps.generatedTextDecision(ai,text)),j(d.caps.generatedTextDecision(ai,text)))});
await log.test('WB_XLSX_ORIGINAL_VERIFICATION_AND_GENERATED_RESTRICTION_KEPT',()=>{const base={filename:'x.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',byte_length:10,sha256:'a'.repeat(64)};assert.equal(w.caps.fileDispatchDecision('alice',{...base,source_kind:'original_provider_file',artifact_key:'provider:test'}).runtime_verification_required,true);assert.equal(w.caps.fileDispatchDecision('alice',{...base,source_kind:'generated_bridge_document',artifact_key:'bridge:test'}).dispatch_allowed,false)});
await log.test('MANIFEST_ORIGINS_EQUAL_IMPLEMENTED_TARGETS_NO_HOST_EXPANSION',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));assert.deepEqual(m.content_scripts[0].matches,j(w.caps.implementedContentScriptPatterns()));assert.equal(m.content_scripts[0].js[0],'shared/ai_delivery_capabilities.js');assert.ok(!m.host_permissions.some(x=>/deepseek|grok|claude|gemini|qwen|kimi/.test(x)))});
function controlFunctions(dir){const source=fs.readFileSync(path.join(dir,'content_script.js'),'utf8');return ['sendButtonCandidates','sendButton'].map(name=>{const marker='function '+name+'(context) {';const start=source.indexOf(marker);assert(start>=0,name);let depth=0,end=source.indexOf('{',start);for(;end<source.length;end++){if(source[end]==='{')depth++;if(source[end]==='}'){depth--;if(depth===0)break;}}return source.slice(start,end+1)}).join('\n')}
function controlSelection(dir,strategy){const custom={id:'custom'},standard={id:'standard'},adapter={id:'synthetic',sendButtonCandidates:()=>[{button:standard,score:1}],sendButton:()=>standard};const box={currentAIAdapter:()=>adapter,WBAIDeliveryCapabilities:{profile:()=>({composer_control_strategy:strategy})},sendButtonProfile:{kind:'fixture'},manualSendButton:()=>custom,targetControlStrategy:()=>strategy,chatgptSendButtonCandidates:()=>[{button:custom,score:3000}],chatgptSendButton:()=>custom,classifyAdapterComposerControl:()=>({kind:'send_active',button:standard})};vm.createContext(box);vm.runInContext(controlFunctions(dir),box);return {button:box.sendButton({})?.id||null,candidates:Array.from(box.sendButtonCandidates({}),x=>x.button.id)}}
await log.test('SYNTHETIC_TARGET_CALIBRATION_USES_CAPABILITY_STRATEGY',()=>{assert.deepEqual(controlSelection(root,'legacy_microphone_completion_v1'),controlSelection(donor,'legacy_microphone_completion_v1'))});
await log.test('UNKNOWN_COMPOSER_STRATEGY_FAILS_CLOSED',()=>{assert.deepEqual(controlSelection(root,'unreviewed_strategy'),controlSelection(donor,'unreviewed_strategy'))});
log.finish({scope:'Current exact donor capability/identity functions versus WB functions; no browser or provider acceptance claim'});
