import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {reporter} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]),box={crypto:crypto.webcrypto,TextEncoder};vm.runInNewContext(fs.readFileSync(path.join(root,'shared/runtime_policy.js'),'utf8'),box);const P=box.WBRuntimePolicy;
function setup(){const data={},clock={at:1000},store={async get(k){return {[k]:structuredClone(data[k])}},async set(v){Object.assign(data,structuredClone(v))}};return {data,clock,store,e:P.create({store,now:()=>clock.at})}}
const req=(fields,scope='one')=>({operation:'synthetic_read',params:{fields,scope}}),value=(id,fields)=>({ok:true,verified:true,request_id:id,external_request_executed:true,result:Object.fromEntries(fields.map(f=>[f,id+':'+f]))});
const policy={enabled:true,mode:'projection',ttl_ms:5000,authority:{reviewed:true,source_revision:'SYNTHETIC_ONLY'},describe:r=>({eligible:true,compatibility_key:r.params.scope,fields:r.params.fields}),verify:(v,r)=>v.ok&&v.verified&&r.params.fields.every(f=>typeof v.result[f]==='string'),project:(v,r)=>({...v,result:Object.fromEntries(r.params.fields.map(f=>[f,v.result[f]]))})};
await log.test('REVIEW_AUTHORITY_REQUIRED_FOR_EVERY_ENABLED_CACHE',async()=>{const {e}=setup(),a=await e.accountKey('a');await assert.rejects(e.cachePut(a,req(['a']),value('r',['a']),{enabled:true,mode:'exact',ttl_ms:5000}),x=>x.code==='CACHE_POLICY_NOT_REVIEWED')});
await log.test('VERIFIED_SUPERSET_PROJECTS_ONLY_REQUESTED_FIELDS',async()=>{const {e}=setup(),a=await e.accountKey('a');assert.equal(await e.cachePut(a,req(['a','b']),value('r',['a','b']),policy),true);const got=await e.cacheGet(a,req(['b']),policy);assert.deepEqual(JSON.parse(JSON.stringify(got.result)),{b:'r:b'});assert.equal(got.external_request_executed,false);assert.equal(got.cache_provenance.source_request_id,'r');assert.equal(got.cache_provenance.projected,true)});
await log.test('BEST_FIT_THEN_NEWEST_MATCHES_DONOR',async()=>{const {e,clock}=setup(),a=await e.accountKey('a');for(const [id,fields]of[['wide',['a','b','c']],['older',['a','b']],['newer',['a','c']]]){clock.at+=100;await e.cachePut(a,req(fields),value(id,fields),policy)}assert.equal((await e.cacheGet(a,req(['a']),policy)).cache_provenance.source_request_id,'newer');await e.cachePut(a,req(['a']),value('exact',['a']),policy);assert.equal((await e.cacheGet(a,req(['a']),policy)).cache_provenance.source_request_id,'exact')});
await log.test('ACCOUNT_SCOPE_AND_COMPATIBILITY_ISOLATION',async()=>{const {e}=setup(),a=await e.accountKey('a'),b=await e.accountKey('b');await e.cachePut(a,req(['a']),value('r',['a']),policy);assert.ok(await e.cacheGet(a,req(['a']),policy));assert.equal(await e.cacheGet(b,req(['a']),policy),null);assert.equal(await e.cacheGet(a,req(['a'],'other'),policy),null)});
await log.test('EXPIRY_AND_AUTHORITY_REVISION_INVALIDATE',async()=>{const {e,clock}=setup(),a=await e.accountKey('a');await e.cachePut(a,req(['a']),value('r',['a']),policy);assert.ok(await e.cacheGet(a,req(['a']),policy));assert.equal(await e.cacheGet(a,req(['a']),{...policy,authority:{...policy.authority,source_revision:'NEXT'}}),null);clock.at=6001;assert.equal(await e.cacheGet(a,req(['a']),policy),null)});
await log.test('REVERIFY_AND_INTEGRITY_REJECT_WITHOUT_REFETCH',async()=>{const {e,data}=setup(),a=await e.accountKey('a');await e.cachePut(a,req(['a']),value('r',['a']),policy);assert.ok(await e.cacheGet(a,req(['a']),policy));assert.equal(await e.cacheGet(a,req(['a']),{...policy,verify:()=>false}),null);for(const v of Object.values(data))if(v.entries)Object.values(v.entries)[0].payload.value.result.a='corrupted';assert.equal(await e.cacheGet(a,req(['a']),policy),null)});
await log.test('FAILED_VERIFICATION_OR_PROJECTION_IS_CACHE_MISS',async()=>{const {e}=setup(),a=await e.accountKey('a');assert.equal(await e.cachePut(a,req(['a']),{...value('bad',['a']),verified:false},policy),false);await e.cachePut(a,req(['a']),value('r',['a']),policy);assert.ok(await e.cacheGet(a,req(['a']),policy));assert.equal(await e.cacheGet(a,req(['a']),{...policy,project(){throw Error('synthetic')}}),null)});
await log.test('DURABLE_READBACK_AND_WORKER_RESTART',async()=>{const {e,store}=setup(),a=await e.accountKey('a');await e.cachePut(a,req(['a']),value('r',['a']),policy);assert.ok(await P.create({store,now:()=>1000}).cacheGet(a,req(['a']),policy));store.set=async()=>{};await assert.rejects(e.cachePut(a,req(['b']),value('new',['b']),policy),x=>x.code==='POLICY_STORAGE_READBACK_FAILED')});
await log.test('DEFAULT_WB_POLICY_STAYS_DISABLED',async()=>{const {e}=setup(),a=await e.accountKey('a');assert.equal(await e.cachePut(a,req(['a']),value('r',['a'])),false);assert.equal(await e.cacheGet(a,req(['a'])),null);assert.equal(P.DEFAULT_CACHE_ENABLED,false)});
if(process.argv[4])await log.test('EXACT_DONOR_FUNCTION_DIFFERENTIAL_CANDIDATE_SELECTION',async()=>{
 const src=fs.readFileSync(path.join(process.argv[4],'service_worker.js'),'utf8'),a=src.indexOf('async function readAnalyticsResultCache('),b=src.indexOf('\nasync function readAnalyticsResultCacheForCurrentSettings',a);assert.ok(a>0&&b>a);
 const rows=[{id:'wide',fields:['a','b','c'],at:1000},{id:'older',fields:['a','b'],at:1100},{id:'newer',fields:['a','c'],at:1200}],entries=Object.fromEntries(rows.map(r=>[r.id,{expires_at:6000,stored_at:r.at,compatibility_key:'one',metrics:r.fields,result:value(r.id,r.fields).result,source_request_id:r.id}]));
 const donor={OzonContract:{normalizeCommand:c=>c,analyticsCoalescingDescriptor:c=>({eligible:true,compatibility_key:c.params.scope,metrics:c.params.metrics}),verifyProviderResponse(c,r){assert.ok(c.params.metrics.every(f=>typeof r[f]==='string'))},projectAnalyticsDataResult:(r,fields,wanted)=>Object.fromEntries(wanted.map(f=>[f,r[f]]))},sellerQuotaIdentity:async()=>({account_hash:'fixture'}),storageGet:async()=>({cache:{accounts:{fixture:{entries}}}}),KEYS:{PROVIDER_RESULT_CACHE:'cache'},normalizedProviderResultCacheState:v=>v,jsonCacheClone:v=>JSON.parse(JSON.stringify(v)),safeAnalyticsCacheMetadata:v=>v};
 vm.runInNewContext(src.slice(a,b)+'\nglobalThis.read=readAnalyticsResultCache',donor);
 const {e,clock}=setup(),account=await e.accountKey('fixture');for(const r of rows){clock.at=r.at;await e.cachePut(account,req(r.fields),value(r.id,r.fields),policy)}clock.at=2000;
 for(const fields of [['a'],['a','b'],['c'],['missing']]){const d=await donor.read({operation:'analytics_data',params:{metrics:fields,scope:'one'}},{},2000),w=await e.cacheGet(account,req(fields),policy);assert.equal(Boolean(w),d.hit);if(w){assert.equal(w.cache_provenance.source_request_id,d.cache.source_request_id);assert.deepEqual(JSON.parse(JSON.stringify(w.result)),JSON.parse(JSON.stringify(d.result)))}}
});

log.finish({scope:'Current donor candidate ranking/projection semantics with synthetic policies only. No WB cache policy and no fetch mechanism.'});
