import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {reporter} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]),box={crypto:crypto.webcrypto,TextEncoder};for(const f of ['runtime_policy.js','entitlement_policy.js']){const p=path.join(root,'shared',f);if(fs.existsSync(p))vm.runInNewContext(fs.readFileSync(p,'utf8'),box)}
const authority={reviewed:true,source_revision:'SYNTHETIC_RULES'},account='a'.repeat(64),base={default_access:'unrestricted',features:[]},restricted={...base,allowed_values:['A','B']},profile={status:'known',account_scope:account,authority_revision:authority.source_revision,verified:true,source_request_id:'explicit-fixture-request',observed_at:1000,expires_at:9000,values:['B']};
const decide=(rule,p=profile,params={},scope=account)=>box.WBEntitlementPolicy.evaluate({authority,rule,params,profile:p,account_scope:scope,at:2000});
await log.test('UNRESTRICTED_DOES_NOT_INVENT_ACCOUNT_ENTITLEMENT',()=>{const r=decide(base,null);assert.equal(r.allowed,true);assert.equal(r.account_access,'not_required');assert.equal(r.probe_performed,false)});
await log.test('UNKNOWN_RULE_FAILS_CLOSED',()=>{const r=decide({default_access:'unknown'});assert.equal(r.allowed,false);assert.equal(r.code,'ENTITLEMENT_RULE_UNKNOWN')});
await log.test('REVIEWED_AUTHORITY_REQUIRED',()=>{assert.throws(()=>box.WBEntitlementPolicy.evaluate({authority:{reviewed:false},rule:base}),e=>e.code==='ENTITLEMENT_POLICY_NOT_REVIEWED')});
await log.test('ENDPOINT_AND_PARAMETER_RESTRICTIONS_INTERSECT',()=>{const r=decide({...restricted,features:[{id:'field',selector:{type:'array_contains_any',field:'fields',values:['restricted']},allowed_values:['B','C']}]},profile,{fields:['restricted']});assert.equal(r.allowed,true);assert.deepEqual(Array.from(r.requirement.allowed_values),['B']);assert.deepEqual(Array.from(r.requirement.reasons),['endpoint_restriction','field'])});
await log.test('UNENTITLED_NOT_SENT_OR_SILENTLY_REWRITTEN',()=>{const p={...profile,values:['C']},params={fields:['keep']};const r=decide(restricted,p,params);assert.equal(r.code,'NOT_ENTITLED');assert.equal(r.external_request_executed,false);assert.equal(params.fields[0],'keep')});
await log.test('STALE_WRONG_ACCOUNT_OR_UNKNOWN_PROFILE_REJECTED',()=>{for(const p of [null,{...profile,status:'unknown'},{...profile,account_scope:'b'.repeat(64)},{...profile,expires_at:1999},{...profile,observed_at:3000},{...profile,authority_revision:'old'},{...profile,verified:false}])assert.equal(decide(restricted,p).code,'ENTITLEMENT_UNKNOWN')});
await log.test('UNRECOGNIZED_SELECTOR_NEVER_IGNORED',()=>{const r=decide({...base,features:[{id:'x',selector:{type:'future_unknown'},allowed_values:['B']}]});assert.equal(r.allowed,false);assert.equal(r.code,'ENTITLEMENT_RULE_UNKNOWN')});
await log.test('CONFLICTING_RULES_AND_EMPTY_GRANTS_REJECTED',()=>{const r=decide({...restricted,features:[{id:'x',selector:{type:'value_in',field:'mode',values:['x']},allowed_values:['C']}]},profile,{mode:'x'});assert.equal(r.code,'ENTITLEMENT_RULE_UNKNOWN');assert.equal(decide({...base,default_access:'restricted',allowed_values:[]}).allowed,false)});
await log.test('PARAMETER_SELECTORS_AND_DATE_BOUNDARY',()=>{for(const [selector,params]of [[{type:'value_in',field:'mode',values:['private']},{mode:'private'}],[{type:'object_array_key_contains_any',field:'sort',key:'key',values:['private']},{sort:[{key:'private'}]}],[{type:'date_older_than_months',field:'date_from',months:1},{date_from:'2020-01-01'}]]){const r=box.WBEntitlementPolicy.evaluate({authority,rule:{...base,features:[{id:'x',selector,allowed_values:['C']}]},params,profile:{...profile,observed_at:Date.parse('2026-09-01'),expires_at:Date.parse('2026-10-01')},account_scope:account,at:Date.parse('2026-09-13')});assert.equal(r.code,'NOT_ENTITLED')}});
await log.test('EXPLICIT_PROFILE_STORAGE_READBACK_AND_RESTART',async()=>{const data={},store={async get(k){return {[k]:structuredClone(data[k])}},async set(v){Object.assign(data,structuredClone(v))}},e=box.WBEntitlementPolicy.create({store});await e.record(profile);const got=await box.WBEntitlementPolicy.create({store}).read(account,authority,2000);assert.equal(got.source_request_id,profile.source_request_id);assert.equal(await e.read('b'.repeat(64),authority,2000),null);store.set=async()=>{};await assert.rejects(e.record({...profile,source_request_id:'next'}),x=>x.code==='ENTITLEMENT_STORAGE_READBACK_FAILED')});
await log.test('PRODUCTION_ADMISSION_USES_OPTIONAL_GENERIC_RULE',()=>{const meta={execution_enabled:true,current:true,effect:'READ',entitlement_policy:{authority,rule:restricted}};assert.throws(()=>box.WBRuntimePolicy.admission(meta,{account_scope:account,entitlement_profile:null,at:2000}),e=>e.code==='ENTITLEMENT_UNKNOWN');assert.equal(box.WBRuntimePolicy.admission(meta,{account_scope:account,entitlement_profile:profile,at:2000}).allowed,true)});
if(process.argv[4])await log.test('EXACT_DONOR_RULE_DIFFERENTIAL_WITH_FIXTURE_LABEL_MAPPING',()=>{
 const donor={OzonOperationRegistry:{operation:()=>({provider:'seller_api',method:'POST',path:'/fixture'})}};vm.runInNewContext(fs.readFileSync(path.join(process.argv[4],'shared/ozon_entitlements.js'),'utf8'),donor);
 const label={A:'PREMIUM',B:'PREMIUM_PLUS',C:'PREMIUM_PRO'},at=Date.parse('2026-09-13T00:00:00Z');
 const cases=[[base,{}],[restricted,{}],[{...restricted,features:[{id:'x',selector:{type:'array_contains_any',field:'fields',values:['restricted']},allowed_values:['B','C']}]},{fields:['restricted']}],[{...base,features:[{id:'x',selector:{type:'date_older_than_months',field:'date_from',months:1},allowed_values:['B']}]},{date_from:'2020-01-01'}]];
 for(const [rule,params]of cases){const dRule={default_access:rule.default_access==='restricted'?'SUBSCRIPTION_RESTRICTED':'ALL_ACCOUNTS',endpoint_allowed_subscription_types:rule.allowed_values?.map(v=>label[v])||null,feature_rules:(rule.features||[]).map(f=>({...f,allowed_subscription_types:f.allowed_values.map(v=>label[v])}))},snapshot={schema:donor.OzonEntitlements.SNAPSHOT_SCHEMA,source:{source_hash:'fixture'},operations:{'POST /fixture':dRule}},d=donor.OzonEntitlements.requirementFor({operation:'fixture',params},snapshot,at),w=box.WBEntitlementPolicy.requirementFor({authority,rule,params,at});assert.equal(w.known,d.known);assert.equal(w.required,d.required);assert.deepEqual(Array.from(w.allowed_values,v=>label[v]).sort(),Array.from(d.allowed_subscription_types).sort())}
});

log.finish({scope:'Provider-neutral endpoint/parameter/account-evidence mechanism. Only synthetic rule values; no WB entitlements activated and no network probe.'});
