import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,identity,key,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),r=reporter(process.argv[3]);
const data=()=>({wbmb_seller_token:'fixture',wbmb_auto_send:true,wbmb_conversation_bindings:{[key]:{...identity,conversation_key:key,binding_id:'binding',revision:1}},[workKey]:{...identity,conversation_key:key,state:'active_visible',revision:1,tab_id:1}});
async function setup(seed=data()){let w;w=boot(root,seed,{onTabMessage:(id,m)=>m.type==='WB_GET_IDENTITY'?{ok:true,identity:w.state.identity,runtime_id:w.state.runtimeId,runtime_generation:w.state.generation}:m.type==='WB_CHECK_USER_DELIVERY'?{ok:true,matched:m.user_turn_id==='proof-user'}:m.type==='WB_CHECK_DELIVERY_STAGE'?{ok:true,staged:true}:undefined});w.req=(type,p={})=>w.call({type,conversation_key:key,actor_id:w.state.runtimeId,runtime_generation:w.state.generation,...p},w.content());return w;}
async function prepare(w){const result=await w.req('WB_EXECUTE_COMMAND',{manual_request_id:'command',command_text:'WB_API_V1 {"operation":"seller_info","params":{}}'});assert.equal(result.ok,true,JSON.stringify(result));const p=await w.req('WB_DELIVERY_PREPARE',{delivery_id:result.delivery_id,baseline_user_turn_ids:['old'],assistant_baseline_ids:[]});assert.equal(p.ok,true);return {...p,delivery_id:result.delivery_id,manual_operation_id:result.manual_operation_id};}
async function test(id,fn){await r.test(id,async()=>{const w=await setup();try{const p=await prepare(w);await fn(w,p);assert.equal(w.counts.provider,1)}finally{w.dispose()}})}
await test('INSERT_COMMIT_DURABLE_BEFORE_SINGLE_PERMIT',async(w,p)=>{const q=await w.req('WB_DELIVERY_INSERT_COMMIT',p);assert.equal(q.insert_allowed,true,JSON.stringify(q));assert.equal(w.data.wbmb_manual_operations[key].insert_state,'committed');assert.equal((await w.req('WB_DELIVERY_INSERT_COMMIT',p)).insert_allowed,false)});
await test('PARALLEL_INSERT_COMMIT_ONE_PERMIT',async(w,p)=>{const qs=await Promise.all(Array.from({length:5},()=>w.req('WB_DELIVERY_INSERT_COMMIT',p)));assert.equal(qs.filter(q=>q.insert_allowed).length,1)});
await test('INSERT_STORAGE_FAILURE_NO_PERMIT',async(w,p)=>{w.state.failWrite=v=>v.wbmb_manual_operations?.[key]?.insert_state==='committed';const q=await w.req('WB_DELIVERY_INSERT_COMMIT',p);assert.equal(q.ok,false);assert.notEqual(q.insert_allowed,true);assert.notEqual(w.data.wbmb_manual_operations[key].insert_state,'committed')});
await test('INSERT_COMMIT_OWNER_REVALIDATION',async(w,p)=>{w.data.wbmb_seller_token='changed';assert.equal((await w.req('WB_DELIVERY_INSERT_COMMIT',p)).code,'DELIVERY_ACCOUNT_CHANGED')});
await test('STAGE_WITHOUT_INSERT_AUTHORITY_REJECTED',async(w,p)=>{assert.equal((await w.req('WB_DELIVERY_STAGE',p)).code,'DELIVERY_INSERT_NOT_COMMITTED')});
await test('NEW_USER_PROOF_RESOLVES_LOST_STAGE_BEFORE_SEND',async(w,p)=>{assert.equal((await w.req('WB_DELIVERY_INSERT_COMMIT',p)).insert_allowed,true);const q=await w.req('WB_MANUAL_DELIVERY_COMPLETE',{manual_operation_id:p.manual_operation_id,delivery_confirmed:true,confirmed_user_turn_id:'proof-user'});assert.equal(q.ok,true,JSON.stringify(q));assert.equal(w.data.wbmb_manual_operations[key].status,'completed');assert.equal(w.data.wbmb_manual_operations[key].send_commit_actor,undefined)});
await r.test('WORKER_RESTART_AFTER_INSERT_COMMIT_NO_NEW_PERMIT',async()=>{let w=await setup();try{let p=await prepare(w);assert.equal((await w.req('WB_DELIVERY_INSERT_COMMIT',p)).insert_allowed,true);const saved=w.data;w.dispose();w=await setup(saved);p={...p,...await w.req('WB_DELIVERY_PREPARE',{delivery_id:p.delivery_id,baseline_user_turn_ids:[],assistant_baseline_ids:[]})};assert.equal(p.insert_state,'committed');assert.equal((await w.req('WB_DELIVERY_INSERT_COMMIT',p)).insert_allowed,false);assert.equal(w.counts.provider,0)}finally{w.dispose()}});
r.finish({scope:'Actual worker insertion commit/storage/restart/owner transaction; simulated UI proof; no real provider requests'});
