import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const root=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:false});const rows=[];const fd=fs.openSync(path.join(out,'results.jsonl'),'wx');
const ctx=vm.createContext({URL,TextEncoder,Uint8Array,ArrayBuffer,crypto:crypto.webcrypto,console,btoa:s=>Buffer.from(s,'binary').toString('base64'),atob:s=>Buffer.from(s,'base64').toString('binary')});
for(const f of ['shared/ai_delivery_capabilities.js','shared/artifact_store.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
async function t(id,fn){let r;try{r={id,status:'PASS',detail:await fn()}}catch(e){r={id,status:'FAIL',error:e.message,stack:e.stack}}rows.push(r);fs.writeSync(fd,JSON.stringify(r)+'\n');fs.fsyncSync(fd);console.log(id,r.status,r.error||'')}
const caps=vm.runInContext('WBAIDeliveryCapabilities',ctx),Store=vm.runInContext('WBArtifactStore',ctx);
await t('P6-CHATGPT-XLSX-STATIC',()=>{const d=caps.fileDispatchDecision('chatgpt',{filename:'report.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',byte_length:100});assert.equal(d.dispatch_allowed,true);assert.equal(d.runtime_verification_required,false)});
await t('P6-ALICE-TXT-STATIC',()=>{const d=caps.fileDispatchDecision('alice',{filename:'full.txt',mime:'text/plain',byte_length:100});assert.equal(d.dispatch_allowed,true);assert.equal(d.runtime_verification_required,false)});
await t('P6-ALICE-XLSX-ORIGINAL-RUNTIME',()=>{const d=caps.fileDispatchDecision('alice',{filename:'provider.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',byte_length:100,source_kind:'original_provider_file',artifact_key:'provider:req-1',sha256:'a'.repeat(64)});assert.equal(d.dispatch_allowed,true);assert.equal(d.runtime_verification_required,true);assert.equal(d.status,'runtime_verification_required')});
await t('P6-ALICE-XLSX-GENERATED-BLOCKED',()=>{const d=caps.fileDispatchDecision('alice',{filename:'generated.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',byte_length:100,source_kind:'generated_bridge_document',artifact_key:'bridge:req-1',sha256:'a'.repeat(64)});assert.equal(d.dispatch_allowed,false)});
await t('P6-ALICE-XLSX-NO-INTEGRITY-BLOCKED',()=>{const d=caps.fileDispatchDecision('alice',{filename:'provider.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',byte_length:100,source_kind:'original_provider_file',artifact_key:'provider:req-1'});assert.equal(d.dispatch_allowed,false)});
await t('P6-ALICE-OVERSIZE-BLOCKED',()=>{const d=caps.fileDispatchDecision('alice',{filename:'x.txt',mime:'text/plain',byte_length:101*1024*1024});assert.equal(d.dispatch_allowed,false);assert.equal(d.reason,'file_too_large_for_adapter')});
await t('P6-ALICE-LARGE-TEXT-DOCUMENT',()=>{const d=caps.generatedTextDecision('alice','x'.repeat(90001));assert.equal(d.representation,'text_document');assert.equal(d.length_metric,'utf16_code_units');assert.equal(d.threshold_status,'calibrated')});
await t('P6-CHATGPT-LARGE-TEXT-DOCUMENT',()=>{const d=caps.generatedTextDecision('chatgpt','x'.repeat(1048001));assert.equal(d.representation,'text_document');assert.equal(d.length_metric,'unicode_code_points')});
await t('P6-ARTIFACT-METADATA-PRESERVED',async()=>{const map=new Map();const backend={async get(k){return map.get(k)||null},async put(r){map.set(r.ref,r)},async remove(k){map.delete(k)},async all(){return [...map.values()]}};const store=Store.create({backend,uuid:()=> '11111111-1111-4111-8111-111111111111',now:()=>1000});const owner={conversation_key:'https://chatgpt.com|11111111-1111-1111-1111-111111111111',binding_id:'b',binding_revision:1,account_scope:'a'.repeat(64)};const d=await store.put(new Uint8Array([1,2,3]),owner,{name:'provider.xlsx',mime:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',requestId:'req',sourceKind:'original_provider_file',artifactKey:'provider:req'});assert.equal(d.source_kind,'original_provider_file');assert.equal(d.artifact_key,'provider:req');assert.match(d.sha256,/^[a-f0-9]{64}$/);const d2=await store.describe(d.ref,owner);assert.deepEqual(JSON.parse(JSON.stringify(d2)),JSON.parse(JSON.stringify(d)))});
await t('P6-ARTIFACT-OWNER-MISMATCH',async()=>{const map=new Map();const backend={async get(k){return map.get(k)||null},async put(r){map.set(r.ref,r)},async remove(k){map.delete(k)},async all(){return [...map.values()]}};const store=Store.create({backend,uuid:()=> '11111111-1111-4111-8111-111111111111',now:()=>1000});const a={conversation_key:'a',binding_id:'b',binding_revision:1,account_scope:'a'.repeat(64)},b={...a,conversation_key:'b'};const d=await store.put(new Uint8Array([1]),a,{requestId:'r'});await assert.rejects(()=>store.describe(d.ref,b),e=>e.code==='ARTIFACT_OWNER_MISMATCH')});
const summary={passed:rows.filter(x=>x.status==='PASS').length,failed:rows.filter(x=>x.status==='FAIL').length,scope:'provider-neutral capability/artifact tests; zero marketplace calls'};fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summary,null,2));fs.closeSync(fd);console.log(summary);process.exitCode=summary.failed?1:0;
