import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,identity} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]);
const sender=(url='https://chatgpt.com/')=>({tab:{id:1,url},url,frameId:0});
const bootRec=(rec,stateIdentity={origin:'https://chatgpt.com',ai_id:'chatgpt',conversation_id:null,status:'unknown',source:'fixture'})=>{const data={'wb_bootstrap_v1:1':rec};const w=boot(root,data);w.state.identity={...stateIdentity};return w};
const rec=()=>({tab_id:1,origin:'https://chatgpt.com',ai_id:'chatgpt',prompt:'BOOT',expires_at:Date.now()+60000,intent_id:'intent-1',status:'pending_identity'});
await log.test('P7-W1-new-chat-pending-editable-no-bind',async()=>{const w=bootRec(rec());try{const r=await w.call({type:'WB_BOOTSTRAP_STATE'},sender());assert.equal(r.ok,true);assert.equal(r.pending,true);assert.equal(r.prompt,'BOOT');assert.equal(r.requires_work_start,true);assert.ok(w.data['wb_bootstrap_v1:1']);assert.equal(w.counts.provider,0)}finally{w.dispose()}});
await log.test('P7-W2-confirmed-identity-consumes-without-binding',async()=>{const w=bootRec(rec(),identity);try{const r=await w.call({type:'WB_BOOTSTRAP_STATE'},sender('https://chatgpt.com/c/'+identity.conversation_id));assert.equal(r.ok,true);assert.equal(r.pending,false);assert.equal(r.identity_resolved,true);assert.equal(r.bound,false);assert.equal(w.data['wb_bootstrap_v1:1'],undefined);assert.equal(w.counts.provider,0)}finally{w.dispose()}});
await log.test('P7-W3-expired-record-is-removed',async()=>{const x=rec();x.expires_at=Date.now()-1;const w=bootRec(x);try{const r=await w.call({type:'WB_BOOTSTRAP_STATE'},sender());assert.equal(r.ok,true);assert.equal(r.pending,false);assert.equal(r.expired,true);assert.equal(w.data['wb_bootstrap_v1:1'],undefined);assert.equal(w.counts.provider,0)}finally{w.dispose()}});
log.finish({scope:'Actual worker bootstrap code; simulated Chrome identity/storage; zero provider calls'});
