import path from 'node:path';import assert from 'node:assert/strict';
import {boot,reporter,identity,key,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]);
const state={wbmb_seller_token:'SYNTHETIC-TOKEN',wbmb_auto_send:true,wbmb_conversation_bindings:{[key]:{...identity,conversation_key:key,binding_id:'b',revision:1}},[workKey]:{state:'active_visible',conversation_key:key,revision:2,tab_id:1,...identity}};
async function test(id,fn){await log.test(id,async()=>{const w=boot(root,structuredClone(state));try{await fn(w);assert.equal(w.counts.provider,0)}finally{w.dispose()}})}
await test('WB_PATH_SCHEMA_USES_OWN_REGISTRY_WITHOUT_BODY_GUESSES',async w=>{const r=w.eval('WBParameterGuidance.describe("analytics_report_download")');assert.deepEqual(Array.from(r.parameter_schema.properties.path.required),['downloadId']);assert.equal(r.schema_completeness,'partial');assert.ok(r.unresolved_schema.length);assert.equal(w.eval('WBParameterGuidance.schema("not_real")'),null)});
await test('HELP_DESCRIBE_EXPOSES_PARTIAL_SCHEMA_AND_NO_FABRICATED_TEMPLATE',async w=>{const r=w.eval('WBCommandProtocol.guidance({operation:"describe",params:{alias:"analytics_report_download"}})');assert.equal(r.operation_card.template,null);assert.equal(r.operation_card.template_runnable,false);assert.ok(r.operation_card.parameter_schema)});
await test('EXACT_INVALID_OPERATION_CORRECTION_REACHES_PERSISTED_LOCAL_RESULT',async w=>{const r=await w.call({type:'WB_EXECUTE_COMMAND',conversation_key:key,manual_request_id:'guidance-fixture',command_text:'WB_API_V1 {"operation":"analytics_report_download","params":{}}'},w.content());assert.equal(r.ok,false);const p=JSON.parse(r.report_text.split('\n').slice(1).join('\n'));const g=p.batch.items[0].guidance;assert.equal(g.status,'operation_parameter_correction');assert.equal(g.operation,'analytics_report_download');assert.ok(g.parameter_schema);assert.equal(g.external_request_executed,false)});
await test('SENSITIVE_OR_UNKNOWN_ATTEMPTS_NEVER_RETURN_PARAMETER_CORRECTION',async w=>{for(const text of ['WB_API_V1 {"operation":"analytics_report_download","params":{"token":"DO-NOT-EXPOSE"}}','WB_API_V1 {"operation":"made_up","params":{}}']){w.context.fixtureInput=text;const p=w.eval('WBCommandProtocol.parseOrError(fixtureInput)');assert.equal(p.entries[0].guidance||null,null);assert.ok(!JSON.stringify(p).includes('DO-NOT-EXPOSE'))}});
await test('GUIDANCE_NEVER_COPIES_RAW_QUERY_KEY_OR_VALUES',async w=>{w.context.fixtureInput='WB_API_V1 '+JSON.stringify({operation:'seller_info',params:{query:{PRIVATE_UNTRUSTED_KEY:'PRIVATE_UNTRUSTED_VALUE'}}});const p=w.eval('WBCommandProtocol.parseOrError(fixtureInput)');assert.equal(p.entries[0].guidance.status,'operation_parameter_correction');assert.ok(!JSON.stringify(p).includes('PRIVATE_UNTRUSTED'))});
log.finish({scope:'Current WB contract-derived partial schema visibility and real worker local error; no provider schema invented or request executed'});
