import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,identity,key,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]);
const seed=()=>({wbmb_seller_token:'synthetic-token',wbmb_auto_send:false,wbmb_conversation_bindings:{[key]:{...identity,binding_id:'binding',revision:1,conversation_key:key}},[workKey]:{state:'active_visible',revision:1,tab_id:1,conversation_key:key,...identity}});
async function test(id,fn){await log.test(id,async()=>{const w=boot(root,seed());try{await fn(w)}finally{w.dispose()}})}
await test('RETIRED_AUTORUN_RUNTIME_ENTRYPOINTS_CLOSED',async w=>{for(const type of ['WB_AUTO_START','WB_AUTO_RESUME','WB_AUTO_COMMAND_READY','WB_AUTO_START_COMMIT_REQUEST','WB_AUTO_START_COMPLETE']){const r=await w.call({type,tab_id:1,conversation_key:key,run_id:'retired',command_text:'WB_API_V1 {"operation":"seller_info","params":{}}'},type==='WB_AUTO_COMMAND_READY'?w.content():w.popup);assert.equal(r.code,'WB_AUTORUN_NON_PRODUCTION',JSON.stringify(r))}assert.equal(w.counts.provider,0);assert.ok(!w.messages.some(m=>m.type==='WB_AUTO_SEND_START'||m.type==='WB_AUTO_BEGIN_WATCH'))});
await test('PERSISTED_RETIRED_WATCH_NOT_RESUMED_ON_CONTENT_RESTART',async w=>{w.data.wbmb_auto_runs={[key]:{run_id:'retired',conversation_key:key,...identity,tab_id:1,status:'waiting_command',binding_snapshot:w.eval(`bindingSnapshot(${JSON.stringify(w.data.wbmb_conversation_bindings[key])})`),watch_id:'old-watch',outgoing_text:'PRESERVED KNOWN TRUTH'}};const r=await w.call({type:'WB_CONTENT_READY',identity,conversation_key:key},w.content());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.auto_watch,null);assert.equal(w.data.wbmb_auto_runs[key].outgoing_text,'PRESERVED KNOWN TRUTH');assert.equal(w.counts.provider,0)});
await test('RETIRED_PROVIDER_PATH_BLOCKED_AT_ACQUISITION_BOUNDARY',async w=>{await assert.rejects(w.eval(`getSettings().then(settings=>wbExecuteProvider('WB_API_V1 {"operation":"seller_info","params":{}}',{mode:'auto',key:${JSON.stringify(key)},id:'retired',tabId:1},settings))`),e=>e.code==='WB_AUTORUN_NON_PRODUCTION');assert.equal(w.counts.provider,0)});
await test('GLOBAL_AND_OTHER_CHAT_STATE_REQUIRE_POPUP_AUTHORITY',async w=>{for(const type of ['WB_GET_SETTINGS_STATE','WB_GET_GLOBAL_SETTINGS_STATE','WB_GET_DIAGNOSTICS','WB_CLEAR_DIAGNOSTICS','WB_SET_MANUAL_MODE','WB_RESOLVE_POPUP_CONTEXT']){const r=await w.call({type,conversation_key:key,tab_id:1,enabled:false},w.content());assert.equal(r.code,'POPUP_AUTHORITY_REQUIRED',type)}assert.equal(w.counts.provider,0)});
await test('MANUAL_PRODUCT_PATH_PRESERVED',async w=>{w.data.wbmb_auto_runs={[key]:{run_id:'old',status:'waiting_command',outgoing_text:'PRESERVED'}};const r=await w.call({type:'WB_EXECUTE_COMMAND',conversation_key:key,manual_request_id:'manual-valid',command_text:'WB_API_V1 {"operation":"seller_info","params":{}}'},w.content());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(w.counts.provider,1)});
for(const change of ['account','generation','route','finish'])await log.test('PORT_REVALIDATES_AFTER_CHUNK_AWAIT_'+change,async()=>{
 const replies=[],w=boot(root,seed(),{onPortMessage:(id,m)=>replies.push(m)});try{
 const scope=await w.eval('WBPolicyEngine.accountKey(JSON.stringify(WBCredentials.normalizeSellerCredentials({clientId:"synthetic-token",tokenType:"personal"})))');
 w.data.wbmb_manual_operations={[key]:{operation_id:'manual',request_id:'result',delivery_id:'delivery',conversation_key:key,...identity,tab_id:1,status:'delivering',account_scope:scope,binding_snapshot:w.eval(`bindingSnapshot(${JSON.stringify(w.data.wbmb_conversation_bindings[key])})`),artifact_refs:[{ref:'wb-file-fixture'}]}};
 w.context.mutateDuringChunk=()=>{if(change==='account')w.data.wbmb_seller_token='other-token';if(change==='generation')w.state.generation='content-g2';if(change==='route')w.state.identity={...identity,conversation_id:'22222222-2222-2222-2222-222222222222'};if(change==='finish')w.data.wbmb_manual_operations[key].finish_requested=true;};
 w.eval('WBArtifactsInstance={chunk:async()=>{await Promise.resolve();mutateDuringChunk();return {data:"PRIVATE_SAVED_BYTES",index:0,total:1}}}');
 w.openPort('fixture','WB_FILE_V1');w.portMessage('fixture',{conversation_key:key,delivery_id:'delivery',ref:'wb-file-fixture',index:0,runtime_generation:'content-g1',actor_id:'content-g1'});await w.settle();assert.equal(replies.length,1);assert.equal(replies[0].ok,false,JSON.stringify(replies));assert.ok(!JSON.stringify(replies).includes('PRIVATE_SAVED_BYTES'));assert.equal(w.counts.provider,0);
 }finally{w.dispose()}
});

await test('PRIMARY_RECOVERY_HIDES_OTHER_ACCOUNT_RESULT',async w=>{w.data.wbmb_manual_operations={[key]:{operation_id:'old',request_id:'old',delivery_id:'old',...identity,status:'delivering',account_scope:'f'.repeat(64),conversation_key:key,tab_id:1,outgoing_text:'PRIVATE_OLD_ACCOUNT_RESULT',binding_snapshot:w.eval(`bindingSnapshot(${JSON.stringify(w.data.wbmb_conversation_bindings[key])})`)}};const r=await w.call({type:'WB_CONTENT_READY',identity,conversation_key:key},w.content());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.manual_recovery,null);assert.ok(!JSON.stringify(r).includes('PRIVATE_OLD_ACCOUNT_RESULT'));assert.equal(w.data.wbmb_manual_operations[key].outgoing_text,'PRIVATE_OLD_ACCOUNT_RESULT')});
await test('SIDE_RECOVERY_HIDES_OTHER_ACCOUNT_RESULT',async w=>{w.data.wb_local_results_v1={old:{operation_id:'old',delivery_id:'old',status:'delivering',account_scope:'f'.repeat(64),conversation_key:key,tab_id:1,outgoing_text:'PRIVATE_OLD_ACCOUNT_RESULT',expires_at:Date.now()+60000}};const r=await w.call({type:'WB_LOCAL_RESULTS_PENDING',conversation_key:key,runtime_generation:'content-g1',actor_id:'content-g1'},w.content());assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.results.length,0);assert.ok(!JSON.stringify(r).includes('PRIVATE_OLD_ACCOUNT_RESULT'));assert.equal(w.data.wb_local_results_v1.old.outgoing_text,'PRIVATE_OLD_ACCOUNT_RESULT')});


await test('CURRENT_ACCOUNT_RECOVERY_RETAINS_FULL_PRIMARY_AND_SIDE_TEXT',async w=>{const account=await w.eval('WBPolicyEngine.accountKey(JSON.stringify(WBCredentials.normalizeSellerCredentials({clientId:"synthetic-token",tokenType:"personal"})))');const r={...identity,status:'delivering',operation_id:'owned',request_id:'owned',delivery_id:'owned',conversation_key:key,tab_id:1,account_scope:account,outgoing_text:'FULL_OWNED_TRUTH',expires_at:Date.now()+60000,binding_snapshot:w.eval(`bindingSnapshot(${JSON.stringify(w.data.wbmb_conversation_bindings[key])})`)};w.data.wbmb_manual_operations={[key]:r};w.data.wb_local_results_v1={side:{...r,side_error:true,operation_id:'side',delivery_id:'side'}};const sync=await w.call({type:'WB_CONTENT_READY',identity,conversation_key:key},w.content());assert.equal(sync.manual_recovery?.outgoing_text,'FULL_OWNED_TRUTH');const pending=await w.call({type:'WB_LOCAL_RESULTS_PENDING',conversation_key:key},w.content());assert.equal(pending.results[0]?.outgoing_text,'FULL_OWNED_TRUTH');assert.equal(w.counts.provider,0)});
await test('LEGACY_DEFAULT_PROMPT_MIGRATES_WITHOUT_REWRITING_CUSTOM_TEXT',async w=>{const old=w.eval('WBRuntime.LEGACY_WORK_START_TEXT');assert.ok(old.includes('Autorun'));w.data.wb_runtime_options_v1={bootstrap_text:old};const migrated=await w.eval('getGlobalAutoStartPrompt()');assert.equal(migrated.is_default,true);assert.ok(!migrated.text.includes('Autorun'));delete w.data.wbmb_global_auto_start_prompt;w.data.wb_runtime_options_v1={bootstrap_text:'My custom Autorun note, keep verbatim'};assert.equal((await w.eval('getGlobalAutoStartPrompt()')).text,'My custom Autorun note, keep verbatim')});

log.finish({scope:'Actual production worker dispatcher and named Port. Explicit NON_PROD project authority; synthetic state transitions; no real provider traffic.'});
