import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,key,pendingKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]);
async function test(id,fn){await log.test(id,async()=>{const w=boot(root);try{await fn(w);assert.equal(w.counts.provider,0)}finally{w.dispose()}})}
const globalSave=w=>w.call({type:'WB_SAVE_RUNTIME_OPTIONS',options:{bootstrap_text:'COMMON NEW START'}});
const get=w=>w.eval('getAutoStartPrompt('+JSON.stringify(key)+')');
await test('GLOBAL_DEFAULT_INHERITED_BY_CONFIRMED_CHAT',async w=>{assert.equal((await globalSave(w)).ok,true);const p=await get(w);assert.equal(p.text,'COMMON NEW START');assert.equal(p.source,'global');assert.equal(p.is_override,false)});
await test('EXPLICIT_CHAT_OVERRIDE_SURVIVES_GLOBAL_CHANGE',async w=>{w.context.k=key;await w.eval('saveAutoStartPrompt(k,"PRIVATE CHAT PROMPT")');await globalSave(w);assert.equal((await get(w)).text,'PRIVATE CHAT PROMPT');w.context.k=key;const state=await w.eval('publicSettingsState(k)');assert.equal(state.auto_start_prompt.is_override,true);assert.equal(state.auto_start_prompt.source,'conversation_override')});
await test('RESET_CHAT_RETURNS_TO_CURRENT_GLOBAL',async w=>{w.context.k=key;await w.eval('saveAutoStartPrompt(k,"PRIVATE CHAT PROMPT")');await globalSave(w);await w.eval('resetAutoStartPrompt(k)');const p=await get(w);assert.equal(p.text,'COMMON NEW START');assert.equal(p.is_override,false)});
await test('OLD_DEFAULT_RECORD_MIGRATES_WITHOUT_PINNING_GLOBAL',async w=>{w.data.wbmb_auto_start_prompts={[key]:{text:w.eval('DEFAULT_AUTO_START_TEXT'),is_default:true}};await globalSave(w);assert.equal((await get(w)).text,'COMMON NEW START');assert.ok(!w.data.wbmb_auto_start_prompts[key])});
await test('LEGACY_CUSTOM_BOOTSTRAP_PRESERVED_ON_MIGRATION',async w=>{w.data.wb_runtime_options_v1={bootstrap_text:'EXISTING CUSTOM BOOTSTRAP'};assert.equal((await get(w)).text,'EXISTING CUSTOM BOOTSTRAP');assert.equal((await w.eval('getGlobalAutoStartPrompt()')).text,'EXISTING CUSTOM BOOTSTRAP')});
await test('START_USES_INHERITED_TEXT_AND_FREEZES_INTENT_HASH',async w=>{await globalSave(w);assert.equal((await w.start()).accepted,true);await w.settle();const m=w.messages.find(m=>m.type==='WB_WORK_SEND_INITIAL_PROMPT');assert.equal(m.text||m.prompt_text,'COMMON NEW START');w.context.text='COMMON NEW START';assert.equal(w.data[pendingKey].prompt_sha256,await w.eval('sha256Hex(text)'))});
await test('GLOBAL_RESET_IS_LOCAL_AND_PRESERVES_CHAT_OVERRIDE',async w=>{w.context.k=key;await w.eval('saveAutoStartPrompt(k,"PRIVATE CHAT PROMPT")');await globalSave(w);const r=await w.call({type:'WB_RESET_GLOBAL_AUTO_START_PROMPT'});assert.equal(r.ok,true);assert.equal((await get(w)).text,'PRIVATE CHAT PROMPT');assert.equal((await w.eval('getGlobalAutoStartPrompt()')).text,w.eval('DEFAULT_AUTO_START_TEXT'))});
await test('CONTENT_CANNOT_RESET_GLOBAL_PROMPT',async w=>{const r=await w.call({type:'WB_RESET_GLOBAL_AUTO_START_PROMPT'},w.content());assert.equal(r.ok,false);assert.equal(r.code,'POPUP_AUTHORITY_REQUIRED')});
await test('EMPTY_GLOBAL_PROMPT_REJECTED_WITHOUT_WRITE',async w=>{await globalSave(w);const r=await w.call({type:'WB_SAVE_RUNTIME_OPTIONS',options:{bootstrap_text:'   '}});assert.equal(r.ok,false);assert.equal((await w.eval('wbOptions()')).bootstrap_text,'COMMON NEW START')});
log.finish({scope:'Actual worker prompt/storage/Start dispatch; synthetic browser acknowledgements; provider calls=0'});
