import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {boot,reporter,key,identity,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]),box={crypto:crypto.webcrypto,TextEncoder};const ctx=vm.createContext(box);for(const f of ['runtime_policy.js','query_planner.js']){const p=path.join(root,'shared',f);if(fs.existsSync(p))vm.runInContext(fs.readFileSync(p,'utf8'),ctx)}
const command=(metrics,scope='same')=>({operation:'fixture_read',params:{metrics,scope}}),entry=(metrics,scope)=>({kind:'api',command:command(metrics,scope)});
const adapter={authority:{reviewed:true,source_revision:'SYNTHETIC_TEST_POLICY_NO_WB_AUTHORITY'},describe:c=>({eligible:true,compatibility_key:c.params.scope}),combine:commands=>{const metrics=[...new Set(commands.flatMap(c=>c.params.metrics))];return metrics.length>14?{eligible:false}:{command:command(metrics,commands[0].params.scope),projection:metrics}},normalize:c=>{assert.equal(c.operation,'fixture_read');return c},project:(result,c,metrics)=>c.params.metrics.map(m=>result[metrics.indexOf(m)])};
const make=a=>box.WBQueryPlanner.create(a);
await log.test('PRODUCTION_IDENTITY_PLAN_NO_OPTIMIZATION_OR_FANOUT',async()=>{const p=await make().build([entry(['a']),{kind:'help',command:{operation:'catalog'}},entry(['b'])]);assert.equal(p.strategy,'explicit_identity');assert.equal(p.groups.length,0);assert.equal(p.physical_call_budget,2);assert.deepEqual(Array.from(p.mappings,r=>r.physical_call_budget),[1,0,1])});
await log.test('CONTIGUOUS_GROUPS_RESPECT_HELP_AND_COMPATIBILITY_BARRIERS',async()=>{const p=await make(adapter).build([entry(['a']),entry(['b']),{kind:'help'},entry(['c']),entry(['d'],'other')]);assert.equal(p.groups.length,1);assert.deepEqual(Array.from(p.groups[0].member_indexes),[0,1]);assert.equal(p.physical_call_budget,3)});
await log.test('UNREVIEWED_ADAPTER_REJECTED',async()=>{assert.throws(()=>make({...adapter,authority:{reviewed:false}}),e=>e.code==='QUERY_POLICY_NOT_REVIEWED')});
await log.test('CAPABILITY_AND_EXECUTION_PHASE_FENCES',async()=>{await assert.rejects(make().build([entry(['a'])],{capability_planned:false}),e=>e.code==='QUERY_PLAN_BEFORE_CAPABILITY');await assert.rejects(make().build([{...entry(['a']),state:'dispatch_committed'}]),e=>e.code==='QUERY_PLAN_EXECUTION_ALREADY_STARTED')});
await log.test('LOGICAL_PROJECTION_COUNTS_ONE_PHYSICAL_REQUEST',async()=>{const e=make(adapter),p=await e.build([entry(['a']),entry(['b'])]),rows=await e.project(p.groups[0],p.entries,{request_id:'physical-one',ok:true,external_request_executed:true,result:[10,20]});assert.deepEqual(Array.from(rows,r=>Array.from(r.result)),[[10],[20]]);assert.equal(e.accounting(rows).physical_request_count,1);assert.equal(e.accounting(rows).logical_result_count,2);assert.ok(rows.every(r=>r.automatic_retry===false))});
await log.test('PROJECTION_FAILURE_PRESERVES_PRIMARY_WITHOUT_REFETCH',async()=>{const e=make({...adapter,project(){throw new Error('fixture failure')}}),p=await e.build([entry(['a']),entry(['b'])]),rows=await e.project(p.groups[0],p.entries,{request_id:'physical-one',ok:true,external_request_executed:true,result:[10,20]});assert.ok(rows.every(r=>r.error.code==='QUERY_PROJECTION_FAILED'&&!r.ok));assert.deepEqual(Array.from(rows[0].result),[10,20]);assert.equal(e.accounting(rows).physical_request_count,1)});
await log.test('PROVIDER_FAILURE_NOT_RETRIED_AS_LOGICAL_COMMANDS',async()=>{let projected=0;const e=make({...adapter,project(){projected++;throw Error()}}),p=await e.build([entry(['a']),entry(['b'])]),rows=await e.project(p.groups[0],p.entries,{request_id:'physical-failed',ok:false,external_request_executed:true,result:{error:'synthetic'}});assert.equal(projected,0);assert.ok(rows.every(r=>r.ok===false&&r.result.error==='synthetic'));assert.equal(e.accounting(rows).physical_request_count,1)});
await log.test('PREFETCH_DEFAULT_OFF_AND_REVIEWED_SINGLE_ACQUISITION',async()=>{const c=command(['a']),base=await make().prefetch(c);assert.equal(base.prefetched,false);const e=make({...adapter,prefetch:c=>({eligible:true,command:command(['a','b']),projection:['a','b']}),projectPrefetch:(r,c,fields)=>adapter.project(r,c,fields)}),p=await e.prefetch(c);assert.equal(p.physical_call_budget,1);assert.equal(p.prefetched,true);assert.deepEqual(Array.from((await e.projectPrefetch(p,{ok:true,result:[10,20]})).result),[10])});
await log.test('WORKER_PERSISTS_IDENTITY_MAPPING_BEFORE_PROVIDER_DISPATCH',async()=>{const data={wbmb_seller_token:'fixture',wbmb_auto_send:false,wbmb_conversation_bindings:{[key]:{...identity,binding_id:'b',revision:1,conversation_key:key}},[workKey]:{state:'active_visible',conversation_key:key,revision:1,tab_id:1,...identity}},w=boot(root,data);try{const r=await w.call({type:'WB_EXECUTE_COMMAND',conversation_key:key,manual_request_id:'plan-test',command_text:'WB_API_V1 {"operation":"seller_info","params":{}}'},w.content());assert.equal(r.ok,true,JSON.stringify(r));const snapshots=w.events.filter(e=>e.type==='storage').flatMap(e=>Object.values(e.value.wbmb_manual_operations||{})).map(o=>o.command_batch?.snapshot).filter(Boolean);assert.ok(snapshots.length);assert.ok(snapshots.every(s=>s.query_plan?.strategy==='explicit_identity'));assert.equal(w.counts.provider,1)}finally{w.dispose()}});
if(process.argv[4])await log.test('DONOR_DIFFERENTIAL_CONTIGUOUS_GROUP_MEMBERSHIP',async()=>{const src=fs.readFileSync(path.join(process.argv[4],'service_worker.js'),'utf8'),start=src.indexOf('function buildBatchQueryPlan('),end=src.indexOf('\nasync function ensureBatchQueryPlanning',start);assert.ok(start>0&&end>start);const donor={OzonContract:{analyticsCoalescingDescriptor:c=>({...adapter.describe(c),metrics:c.params.metrics}),buildAnalyticsCoalescedCommand:commands=>{const v=adapter.combine(commands);return {command:v.command,metrics:v.projection,compatibility_fingerprint:'fixture'}},commandFingerprint:c=>JSON.stringify(c)}};vm.runInNewContext(src.slice(start,end)+'\nglobalThis.build=buildBatchQueryPlan;',donor);const entries=[entry(['a']),entry(['b']),{kind:'help'},entry(['c']),entry(['d'],'other')],p=await make(adapter).build(entries),d=donor.build(entries.map(e=>({...e,kind:e.kind==='api'?'command':e.kind})));assert.deepEqual(JSON.parse(JSON.stringify(p.groups.map(g=>g.member_indexes))),JSON.parse(JSON.stringify(d.groups.map(g=>g.member_indexes))))});
log.finish({scope:'Generic planner with explicit synthetic policies; shipped WB policy remains absent/disabled; actual worker identity-plan persistence, fixture fetch only'});
