import path from 'node:path';
import assert from 'node:assert/strict';
import {boot,reporter,key,workKey,identity} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),r=reporter(process.argv[3]),all=[];
const recKey='wb_work_recovery_v1:'+key;
async function make(){const w=boot(root);all.push(w);await w.eval(`bindConversation({tab_id:1,origin:${JSON.stringify(identity.origin)},conversation_id:${JSON.stringify(identity.conversation_id)}})`);w.data[workKey]={version:1,state:'active_visible',revision:10,conversation_key:key,tab_id:1,origin:identity.origin,ai_id:'chatgpt',conversation_id:identity.conversation_id};return w;}
async function seed(w,phase='renewal_committed',hidden=false){const b=await w.eval(`bindingForConversationKey(${JSON.stringify(key)})`);w.data[workKey].state=phase==='visibility_committed'?'active_visible':'recovering';w.data[workKey].revision=phase==='visibility_committed'?11:10;w.data[recKey]={version:1,recovery_id:'rec-1',revision:10,conversation_key:key,tab_id:1,origin:identity.origin,ai_id:'chatgpt',conversation_id:identity.conversation_id,binding_id:b.binding_id,binding_revision:b.revision,phase,expires_at:new Date(Date.now()+30000).toISOString(),created_at:new Date().toISOString(),old_runtime_id:'old-physical',old_runtime_generation:'old-logical',new_runtime_generation:'new-logical',assistant_baseline_ids:['a-old'],expected_visible:!hidden};}
const resume=w=>w.call({type:'WB_WORK_RECOVERY_RESUME',identity:w.state.identity,runtime_id:w.state.runtimeId,runtime_generation:w.state.generation},w.content());
const act=(w,action='refresh')=>w.call({type:'WB_WORK_ACTION',action,tab_id:1,identity:w.state.identity});
const state=w=>w.call({type:'WB_WORK_STATE',conversation_key:key},w.content());
await r.test('WAKE_RENEWAL_NO_REINIT_NO_SEND',async()=>{const a=await make();await seed(a);const w=boot(root,structuredClone(a.data));all.push(w);const q=await resume(w);assert.equal(q.ok,true,JSON.stringify(q));assert.equal(w.data[recKey].phase,'completed');assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);assert.equal(w.counts.provider,0);assert.equal(w.counts.promptDispatch,0);});
await r.test('WAKE_OLD_RUNTIME_NO_REINIT',async()=>{const w=await make();await seed(w);w.state.runtimeId='old-physical';const q=await resume(w);assert.equal(q.pending,true);assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);});
await r.test('VISIBILITY_PENDING_MUST_NOT_ADMIT_MANUAL',async()=>{const w=await make();await seed(w,'visibility_committed');const q=await state(w);assert.notEqual(q.work.state,'active_visible');assert.equal(await w.eval(`getManualMode(${JSON.stringify(key)})`),false);});
await r.test('COMPLETED_WRITE_FAILURE_FAILS_CLOSED',async()=>{const w=await make();w.state.failWrite=v=>v[recKey]?.phase==='completed';const q=await act(w);assert.equal(q.ok,false);assert.notEqual((await state(w)).work.state,'active_visible');assert.equal(await w.eval(`getManualMode(${JSON.stringify(key)})`),false);});
await r.test('COMPLETED_AND_FAILED_WRITE_FAILURE_FAILS_CLOSED',async()=>{const w=await make();w.state.failWrite=v=>['completed','failed'].includes(v[recKey]?.phase);const q=await act(w);assert.equal(q.ok,false);assert.notEqual((await state(w)).work.state,'active_visible');});
await r.test('WORK_WRITE_FAILURE_WITH_INTENT_BLOCKS_ADMISSION',async()=>{const w=await make();w.state.failWrite=v=>v[workKey]?.state==='recovering';const q=await act(w);assert.equal(q.ok,false);assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);assert.notEqual((await state(w)).work.state,'active_visible');});
await r.test('WAKE_VISIBILITY_RECHECK_WITHOUT_REINIT',async()=>{const w=await make();await seed(w,'visibility_committed');const q=await resume(w);assert.equal(q.ok,true,JSON.stringify(q));assert.equal(w.data[recKey].phase,'completed');assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);});
await r.test('CONCURRENT_WAKE_ONE_HANDSHAKE',async()=>{const w=await make();await seed(w);await Promise.all([resume(w),resume(w),resume(w)]);assert.equal(w.messages.filter(m=>m.type==='WB_WORK_RUNTIME_RENEW').length,1);assert.equal(w.data[recKey].phase,'completed');});
await r.test('CONCURRENT_VISIBILITY_WAKE_ONE_HANDSHAKE',async()=>{const w=await make();await seed(w,'visibility_committed');await Promise.all([resume(w),resume(w)]);assert.equal(w.messages.filter(m=>m.type==='WB_WORK_RUNTIME_RENEW').length,1);assert.equal(w.data[recKey].phase,'completed');});
await r.test('WAKE_HIDDEN_STATE_PRESERVED',async()=>{const w=await make();await seed(w,'renewal_committed',true);await resume(w);assert.equal(w.data[workKey].state,'active_hidden');});
await r.test('MALFORMED_EXPIRY_REJECTED',async()=>{const w=await make();await seed(w);w.data[recKey].expires_at='invalid';const q=await resume(w);assert.equal(q.ok,false);assert.notEqual(w.data[workKey].state,'active_visible');});
await r.test('MALFORMED_GENERATION_REJECTED',async()=>{const w=await make();await seed(w);w.data[recKey].new_runtime_generation='';const q=await resume(w);assert.equal(q.ok,false);assert.notEqual(w.data[workKey].state,'active_visible');});
await r.test('WAKE_BINDING_CHANGE_REJECTED',async()=>{const w=await make();await seed(w);w.data[recKey].binding_revision++;const q=await resume(w);assert.equal(q.ok,false);assert.notEqual(w.data[workKey].state,'active_visible');});
await r.test('WAKE_WRONG_TAB_REJECTED',async()=>{const w=await make();await seed(w);const q=await w.call({type:'WB_WORK_RECOVERY_RESUME',identity:w.state.identity,runtime_id:w.state.runtimeId,runtime_generation:w.state.generation},{...w.content(),tab:{...w.content().tab,id:2}});assert.equal(q.ok,false);assert.equal(w.messages.filter(m=>['WB_WORK_RUNTIME_RENEW','WB_RUNTIME_REFRESH'].includes(m.type)).length,0);});
await r.test('FINISH_THEN_WAKE_NEVER_ACTIVATES',async()=>{const w=await make();await seed(w);assert.equal((await act(w,'finish')).ok,true);await resume(w);assert.equal(w.data[workKey].state,'inactive');assert.equal(w.data[recKey].phase,'cancelled');assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);});
await r.test('EXPIRED_VISIBILITY_FAILS_CLOSED',async()=>{const w=await make();await seed(w,'visibility_committed');w.data[recKey].expires_at='2000-01-01T00:00:00.000Z';await resume(w);assert.notEqual((await state(w)).work.state,'active_visible');assert.equal(w.data[recKey].phase,'expired');});
await r.test('WAKE_INTENT_DOES_NOT_REINIT',async()=>{const w=await make();await seed(w,'intent');const q=await resume(w);assert.equal(q.ok,false);assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0);});
await r.test('WAKE_WRONG_GENERATION_REJECTED',async()=>{const w=await make();await seed(w);const q=await w.call({type:'WB_WORK_RECOVERY_RESUME',identity:w.state.identity,runtime_id:w.state.runtimeId,runtime_generation:'forged'},w.content());assert.equal(q.ok,false);assert.equal(w.messages.filter(m=>m.type==='WB_WORK_RUNTIME_RENEW').length,0);});
for(const w of all)w.dispose();r.finish({scope:'Actual production dispatcher and durable storage recreation; adversarial mocks only; zero marketplace calls'});
