import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,key,identity,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]);const command='WB_API_V1 {"operation":"seller_info","params":{}}';
const deep={};let cursor=deep;for(let i=0;i<70;i++)cursor=cursor.child={};cursor.secretEcho='SYNTHETIC-SECRET';
async function test(id,fn){await log.test(id,async()=>{const replies=[],w=boot(root,{}, {onPortMessage:(id,m)=>replies.push(m)});w.portReplies=replies;try{await fn(w)}finally{w.dispose()}})}
function factory(w,raw,options={}){let calls=0,captured=[];const provider=w.context.WBProviderFactory.createWBProvider({fetchImpl:async()=>{calls++;return new Response(raw,{status:200,headers:{'Content-Type':'application/json'}})},quarantineSink:async(bytes,info)=>{captured.push({bytes,info});return {ref:'wb-file-11111111-1111-4111-8111-111111111111',sha256:'a'.repeat(64),byte_length:bytes.length}},...options});return {provider,captured,calls:()=>calls,run:()=>provider.executeCommand(command,{token:'SYNTHETIC-SECRET'})}}
await test('POST_HTTP_SANITATION_FAILURE_PRESERVES_HTTP_AND_RAW_LOCALLY',async w=>{const f=factory(w,JSON.stringify(deep)),r=await f.run();assert.equal(r.ok,false);assert.equal(r.http_status,200);assert.equal(r.verification,'RESPONSE_PROCESSING_FAILED');assert.equal(f.calls(),1);assert.equal(f.captured.length,1);assert.equal(new TextDecoder().decode(f.captured[0].bytes),JSON.stringify(deep));assert.ok(!r.report_text.includes('SYNTHETIC-SECRET'));assert.ok(r.report_text.includes('chat_access_blocked'));assert.equal(r.artifact_refs.length,0)});
await test('DECLARED_JSON_EMPTY_BODY_IS_NOT_JSON_SUCCESS',async w=>{const f=factory(w,'');const r=await f.run();assert.equal(r.ok,false);assert.equal(r.http_status,200);assert.equal(r.verification,'MALFORMED_DECLARED_JSON');assert.equal(f.calls(),1)});
await test('VALID_JSON_NULL_IS_NOT_CONFUSED_WITH_PARSE_FAILURE',async w=>{const f=factory(w,'null'),r=await f.run();assert.equal(r.ok,true);assert.equal(r.verification_details.parse,'json');assert.equal(r.verification_details.schema,'not_configured');assert.equal(f.calls(),1)});
await test('SCHEMA_FRAMEWORK_CAN_REJECT_WITHOUT_INVENTED_WB_SCHEMA',async w=>{const f=factory(w,'{"fixture":"wrong"}',{verificationPolicy:{reviewed:true,source_revision:'SYNTHETIC_ONLY',schema:{type:'object',required:['count'],properties:{count:{type:'integer'}}}}}),r=await f.run();assert.equal(r.ok,false);assert.equal(r.http_status,200);assert.equal(r.verification_details.schema,'failed');assert.equal(f.calls(),1)});
await test('SEMANTIC_ERROR_FRAMEWORK_IS_PROVIDER_ADAPTER_OWNED',async w=>{const f=factory(w,'{"fixture_error":true}',{verificationPolicy:{reviewed:true,source_revision:'SYNTHETIC_ONLY',semanticError:value=>value.fixture_error?{code:'SYNTHETIC_PROVIDER_ERROR'}:null}}),r=await f.run();assert.equal(r.ok,false);assert.equal(r.verification_details.semantic,'error');assert.equal(f.calls(),1)});
await test('PROTOTYPE_RESPONSE_KEYS_REJECTED_WITH_KNOWN_HTTP',async w=>{const f=factory(w,'{"__proto__":{"danger":true}}'),r=await f.run();assert.equal(r.ok,false);assert.equal(r.http_status,200);assert.ok(r.report_text.includes('UNSAFE_RESPONSE_KEY'));assert.equal(f.calls(),1)});
await test('FAILED_QUARANTINE_STORAGE_DOES_NOT_CHANGE_PROVIDER_TRUTH',async w=>{const f=factory(w,JSON.stringify(deep),{quarantineSink:async()=>{throw Error('local storage')}}),r=await f.run();assert.equal(r.ok,false);assert.equal(r.http_status,200);assert.ok(r.report_text.includes('raw_retention_failed'));assert.equal(f.calls(),1)});
await test('WORKER_QUARANTINED_RESPONSE_CANNOT_USE_LOCAL_FILE_DELIVERY',async w=>{
 Object.assign(w.data,{wbmb_seller_token:'SYNTHETIC-SECRET',wbmb_auto_send:false,wbmb_conversation_bindings:{[key]:{...identity,conversation_key:key,binding_id:'b',revision:1}},[workKey]:{state:'active_visible',conversation_key:key,revision:1,tab_id:1,...identity}});
 const saved=new Map();w.context.artifactBackend={get:async k=>saved.get(k)||null,put:async r=>saved.set(r.ref,r),remove:async k=>saved.delete(k),all:async()=>[...saved.values()]};w.eval('WBArtifactsInstance=WBArtifactStore.create({backend:artifactBackend})');w.context.fetch=async()=>{w.counts.provider++;return new Response(JSON.stringify(deep),{status:200,headers:{'Content-Type':'application/json'}})};
 const r=await w.call({type:'WB_EXECUTE_COMMAND',conversation_key:key,manual_request_id:'response-test',command_text:command},w.content());assert.equal(r.ok,false);assert.equal(w.counts.provider,1);const snapshot=w.data.wbmb_manual_operations[key].command_batch.snapshot;assert.equal(snapshot.items[0].http_status,200);assert.equal(snapshot.items[0].state,'error');assert.equal(saved.size,1);const captured=[...saved.values()][0];assert.equal(captured.source_kind,'unverified_provider_response');w.context.ref=captured.ref;w.context.key=key;await assert.rejects(w.eval('wbReadLocalFile({ref},{key})'),e=>e.code==='LOCAL_FILE_TYPE_MISMATCH');assert.equal(w.counts.provider,1);assert.ok(!r.report_text.includes('SYNTHETIC-SECRET'));w.openPort('quarantine','WB_FILE_V1');w.portMessage('quarantine',{conversation_key:key,delivery_id:r.delivery_id,manual_operation_id:r.manual_operation_id,actor_id:w.state.runtimeId,runtime_generation:w.state.generation,ref:captured.ref,index:0});await w.settle();assert.equal(w.portReplies[0]?.ok,false);assert.equal(w.portReplies[0]?.code,'ARTIFACT_NOT_IN_DELIVERY');assert.ok(!w.portReplies[0]?.base64);
});
log.finish({scope:'Actual worker/provider pipeline with synthetic response bodies/schema/error adapters; no real WB calls; no WB schema activated'});
