import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,key,identity,pendingKey,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),log=reporter(process.argv[3]);
async function test(id,fn){await log.test(id,async()=>{const w=boot(root,{wbmb_seller_token:'fixture',wbmb_conversation_bindings:{[key]:{...identity,conversation_key:key,binding_id:'binding1',revision:1}}});try{assert.equal((await w.start()).accepted,true);await w.settle();await fn(w);assert.equal(w.counts.provider,0)}finally{w.dispose()}})}
const message=w=>({...w.data[pendingKey],identity:w.state.identity,runtime_generation:w.state.generation,actor_id:'fixture-actor',baseline_user_turn_ids:[],assistant_baseline_ids:[]});
const commit=w=>w.call({...message(w),type:'WB_WORK_START_COMMIT_REQUEST'},w.content());
await test('BINDING_REVISION_CHANGE_AFTER_START_REJECTS_COMMIT',async w=>{w.data.wbmb_conversation_bindings[key].revision=2;const r=await commit(w);assert.equal(r.ok,false);assert.equal(r.code,'WORK_START_BINDING_CHANGED')});
await test('ACCOUNT_CHANGE_DURING_COMMIT_DIAGNOSTIC_REJECTS_PERMIT',async w=>{w.state.failWrite=v=>{if(v.wbmb_diagnostics?.at(-1)?.event==='WORK_START_SEND_COMMIT_ACK')w.data.wbmb_seller_token='changed';return false};const r=await commit(w);assert.equal(r.ok,false);assert.equal(r.code,'WORK_START_ACCOUNT_CHANGED');assert.ok(w.data[pendingKey].send_commit_actor_id)});
await test('GENERATION_CHANGE_DURING_COMMIT_DIAGNOSTIC_REJECTS_PERMIT',async w=>{w.state.failWrite=v=>{if(v.wbmb_diagnostics?.at(-1)?.event==='WORK_START_SEND_COMMIT_ACK')w.state.generation='content-g2';return false};const r=await commit(w);assert.equal(r.ok,false);assert.equal(r.code,'WORK_START_GENERATION_MISMATCH')});
await test('ACTIVATION_READBACK_REQUIRED_BEFORE_VISIBLE_ACK',async w=>{assert.equal((await commit(w)).click_allowed,true);let m=message(w);assert.equal((await w.call({...m,type:'WB_WORK_START_SEND_OUTCOME',click_event_observed:true,composer_empty:true,user_turn_id:'user-new'},w.content())).send_outcome,'sent_acknowledged');const original=w.context.chrome.storage.local.set;w.context.chrome.storage.local.set=async v=>{if(v[workKey]?.state==='active_visible')return;return original(v)};const r=await w.call({...message(w),type:'WB_WORK_PENDING_IDENTITY',first_response_complete:true,assistant_turn_id:'assistant-new'},w.content());assert.equal(r.ok,false);assert.equal(r.code,'WORK_START_ACTIVATION_READBACK_FAILED');assert.notEqual(w.data[workKey]?.state,'active_visible')});
log.finish({scope:'Actual Work Start transaction; adversarial storage/diagnostic timing; fixture UI; real provider requests=0'});
