import path from 'node:path';import assert from 'node:assert/strict';import {boot,reporter,key,identity,pendingKey,workKey} from './worker_harness.mjs';
const root=path.resolve(process.argv[2]),r=reporter(process.argv[3]);
const binding={...identity,conversation_key:key,binding_id:'binding1',revision:1};
const action=(w,action)=>w.call({type:'WB_WORK_ACTION',action,tab_id:1,identity:w.state.identity});
async function test(id,state,fn){await r.test(id,async()=>{const w=boot(root,{wbmb_seller_token:'fixture',wbmb_conversation_bindings:{[key]:binding},[workKey]:{state,revision:10,conversation_key:key,tab_id:1,...identity}});try{await fn(w);assert.equal(w.counts.provider,0)}finally{w.dispose()}})}
await test('RESUME_ERROR_IS_NOT_INACTIVE','error',async w=>{const before=structuredClone(w.data[workKey]);const q=await action(w,'toggle');assert.equal(q.ok,false);assert.equal(q.code,'WORK_SESSION_NOT_INACTIVE');assert.deepEqual(w.data[workKey],before)});
await test('RESUME_REJECTS_UNFINISHED_OPERATION','inactive',async w=>{w.data.wbmb_manual_operations={[key]:{operation_id:'saved',conversation_key:key,status:'delivering',tab_id:1}};const q=await action(w,'toggle');assert.equal(q.ok,false);assert.equal(q.code,'WORK_RESUME_OPERATION_ACTIVE');assert.equal(w.data[workKey].state,'inactive');assert.equal(w.counts.promptDispatch,0)});
await test('SHOW_ACK_FAILURE_RETURNS_HIDDEN','active_hidden',async w=>{w.state.visibility=false;assert.equal((await action(w,'toggle')).ok,false);assert.equal(w.data[workKey].state,'active_hidden');assert.equal(await w.eval(`getManualMode(${JSON.stringify(key)})`),false)});
await test('HIDE_ACK_FAILURE_KEEPS_HIDDEN','active_visible',async w=>{w.state.visibility=false;assert.equal((await action(w,'toggle')).ok,false);assert.equal(w.data[workKey].state,'active_hidden');assert.equal(await w.eval(`getManualMode(${JSON.stringify(key)})`),false)});
await test('REFRESH_SEMANTIC_STORAGE_READBACK','active_hidden',async w=>{w.state.reorderReads=true;const q=await action(w,'refresh');assert.equal(q.ok,true,JSON.stringify(q));assert.equal(w.data[workKey].state,'active_hidden');assert.equal(w.counts.promptDispatch,0)});
await test('REFRESH_ERROR_STATE_REJECTED','error',async w=>{assert.equal((await action(w,'refresh')).ok,false);assert.equal(w.messages.filter(m=>m.type==='WB_RUNTIME_REFRESH').length,0)});
async function activate(w){assert.equal((await w.start()).accepted,true);await w.settle();const m=()=>({...w.data[pendingKey],identity:w.state.identity,runtime_generation:w.state.generation,actor_id:'actor-1',baseline_user_turn_ids:[],assistant_baseline_ids:[]});assert.equal((await w.call({...m(),type:'WB_WORK_START_COMMIT_REQUEST'},w.content())).click_allowed,true);assert.equal((await w.call({...m(),type:'WB_WORK_START_SEND_OUTCOME',click_event_observed:true,composer_empty:true,user_turn_id:'user-new'},w.content())).send_outcome,'sent_acknowledged');return {...m(),type:'WB_WORK_PENDING_IDENTITY',first_response_complete:true,assistant_turn_id:'assistant-new'};}
await test('FINISH_WINS_OVER_LATE_START_VISIBILITY_FAILURE','inactive',async w=>{const m=await activate(w),original=w.context.chrome.tabs.sendMessage;let release,arrived;const seen=new Promise(res=>arrived=res);w.context.chrome.tabs.sendMessage=(id,msg,cb)=>{if(msg.type==='WB_WORK_VISIBILITY'&&msg.work.state==='active_visible'){release=()=>cb({ok:false,applied:false});arrived();}else original(id,msg,cb)};const observation=w.call(m,w.content());await seen;assert.equal((await action(w,'finish')).work.state,'inactive');release();const q=await observation;assert.equal(q.ok,false);assert.equal(q.code,'WORK_SESSION_STALE_EVENT');assert.equal(w.data[workKey].state,'inactive')});
await test('START_POST_ACK_GENERATION_RECHECK','inactive',async w=>{const m=await activate(w),original=w.context.chrome.tabs.sendMessage;w.context.chrome.tabs.sendMessage=(id,msg,cb)=>{if(msg.type==='WB_WORK_VISIBILITY'&&msg.work.state==='active_visible'){w.state.generation='content-g2';cb({ok:true,applied:true});}else original(id,msg,cb)};const q=await w.call(m,w.content());assert.equal(q.ok,false);assert.notEqual(w.data[workKey].state,'active_visible')});
r.finish({scope:'Current donor Work Resume/Show/Hide/Refresh semantics; late Start acknowledgement vs Finish; fixture browser APIs; no provider traffic'});
